### ISSUE TITLE
no `simd` in the root

### ISSUE THREAD

**Issue by svenstaro** [AdamNiederer/vektor#2]
So I'm trying to compile the faster crate but then this crate fails with 
```
6 | use core::simd;
  |     ^^^^^^^^^^ no `simd` in the root
```

Using `rustc 1.29.0-nightly (6a1c0637c 2018-07-23)`. What's wrong here?

**Comment by AdamNiederer** [comment]
Ah, such is life with the nightly compiler. They must've removed `core::simd` from the standard library recently.

**Comment by codri** [comment]
Was able to make it build by switching references from `core::simd` to `https://github.com/rust-lang-nursery/packed_simd`, added a depedency and changed the `use`:

```diff
-use crate::simd::*;
+use packed_simd::*;
```

Now it compiles, not sure if it works though. @AdamNiederer shall I make a pull request? or am I missing something?

Also, it's a shame that faster is nightly only, I'd take the stable x86 and x86_64 support that's in stable and actually works. I'd start using that in a heartbeat.

**Comment by AdamNiederer** [comment]
> Was able to make it build by switching references from core::simd to https://github.com/rust-lang-nursery/packed_simd, added a depedency and changed the use:
> 
> -use crate::simd::*;
> +use packed_simd::*;
> 
> Now it compiles, not sure if it works though. @AdamNiederer shall I make a pull request? or am I missing something?

Hey, thanks for the tip. I'll see if it's works as expected shortly - it's by the same person who wrote the majority of `core::simd`, so it my hunch is it should work in the near-term.

> Also, it's a shame that faster is nightly only, I'd take the stable x86 and x86_64 support that's in stable and actually works. I'd start using that in a heartbeat.

I agree - I began writing `faster` under the assumption that cross-platform SIMD types would closely follow the platform specific intrinsics' stabilization. Hopefully it won't be too much longer.
